name: Deploy react website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Repository download
      - uses: actions/checkout@v4

      # Install Node
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      # Install dependencies
      - run: npm install

      # Build Vite project
      - run: npm run build

      # Configure SSH
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      # Copy website
      - name: Upload website
  		run: |
    	  rsync -avz --delete \
      	  -e "ssh -i ~/.ssh/id_ed25519" \
      	  dist/ \
      	  ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/dist/

	  -name: Install website
	  	run: |
	  	  ssh -i ~.ssh/id_ed25519 ubuntu@{{ secrets.EC2_HOST }} << 'EOF'
	  	    sudo rm -rf /var/www/html/*
	  	    sudo cp -r /home/ubuntu/dist/* /var/www/html
	  	  EOF
